module.exports = {
  plugins: ["stylelint-use-logical-spec", "stylelint-order"],
  rules: {
    "alpha-value-notation": "number",
    "annotation-no-unknown": true,
    "at-rule-allowed-list": null,
    "at-rule-disallowed-list": "extend",
    "at-rule-empty-line-before": null,
    "at-rule-no-unknown": null,
    "at-rule-no-vendor-prefix": true,
    "at-rule-property-required-list": null,
    "block-no-empty": true,
    "color-function-notation": "modern",
    "color-hex-alpha": "never",
    "color-hex-length": "short",
    "color-named": "never",
    "color-no-hex": true,
    "color-no-invalid-hex": true,
    "comment-empty-line-before": [
      "always",
      {
        except: ["first-nested"],
        ignore: ["after-comment", "stylelint-commands"],
      },
    ],
    "comment-no-empty": true,
    "comment-pattern": null,
    "comment-whitespace-inside": "always",
    "comment-word-disallowed-list": null,
    "custom-media-pattern": null,
    "custom-property-empty-line-before": "never",
    "custom-property-no-missing-var-function": true,
    "custom-property-pattern": null,
    "declaration-block-no-duplicate-custom-properties": true,
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-redundant-longhand-properties": null,
    "declaration-block-no-shorthand-property-overrides": true,
    "declaration-block-single-line-max-declarations": 1,
    "declaration-property-max-values": null,
    "declaration-empty-line-before": [
      "always",
      {
        except: ["after-comment", "after-declaration", "first-nested"],
      },
    ],
    "declaration-no-important": true,
    "declaration-property-unit-allowed-list": null,
    "declaration-property-unit-disallowed-list": [
      {
        "font-size": ["em", "rem"],
      },
      {
        "line-height": ["px", "em", "rem"],
      },
    ],
    "declaration-property-value-allowed-list": null,
    "declaration-property-value-disallowed-list": null,
    "font-family-name-quotes": "always-where-recommended",
    "font-family-no-duplicate-names": true,
    "font-family-no-missing-generic-family-keyword": true,
    "font-weight-notation": "numeric",
    "function-allowed-list": null,
    "function-disallowed-list": null,
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-name-case": "lower",
    "function-url-no-scheme-relative": true,
    "function-url-quotes": "always",
    "function-url-scheme-allowed-list": null,
    "function-url-scheme-disallowed-list": null,
    "hue-degree-notation": "number",
    "import-notation": "string",
    "keyframe-block-no-duplicate-selectors": true,
    "keyframe-declaration-no-important": true,
    "keyframes-name-pattern": null,
    "keyframe-selector-notation": "percentage",
    "length-zero-no-unit": true,
    "max-nesting-depth": 3,
    "media-feature-name-allowed-list": null,
    "media-feature-name-disallowed-list": null,
    "media-feature-name-no-unknown": true,
    "media-feature-name-no-vendor-prefix": true,
    "media-feature-name-value-allowed-list": null,
    "named-grid-areas-no-invalid": true,
    "no-descending-specificity": null,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "no-empty-source": true,
    "no-invalid-double-slash-comments": true,
    "no-invalid-position-at-import-rule": true,
    "no-irregular-whitespace": true,
    "no-unknown-animations": null,
    "number-max-precision": 8,
    "property-allowed-list": null,
    "property-disallowed-list": null,
    "property-no-unknown": true,
    "property-no-vendor-prefix": true,
    "rule-empty-line-before": [
      "always",
      {
        except: ["first-nested"],
        ignore: ["after-comment"],
      },
    ],
    "rule-selector-property-disallowed-list": null,
    "selector-attribute-name-disallowed-list": null,
    "selector-attribute-operator-allowed-list": null,
    "selector-attribute-operator-disallowed-list": null,
    "selector-attribute-quotes": "always",
    "selector-class-pattern": null,
    "selector-combinator-allowed-list": null,
    "selector-combinator-disallowed-list": null,
    "selector-disallowed-list": null,
    "selector-id-pattern": null,
    "selector-max-attribute": 1,
    "selector-max-class": null,
    "selector-max-combinators": 1,
    "selector-max-compound-selectors": 3,
    "selector-max-id": 0,
    "selector-max-pseudo-class": null,
    "selector-max-specificity": null,
    "selector-max-type": null,
    "selector-max-universal": null,
    "selector-nested-pattern": null,
    "selector-no-qualifying-type": [
      true,
      {
        ignore: ["attribute"],
      },
    ],
    "selector-no-vendor-prefix": true,
    "selector-not-notation": null,
    "selector-pseudo-class-allowed-list": null,
    "selector-pseudo-class-disallowed-list": null,
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-allowed-list": null,
    "selector-pseudo-element-colon-notation": "double",
    "selector-pseudo-element-disallowed-list": null,
    "selector-pseudo-element-no-unknown": true,
    "selector-type-case": "lower",
    "selector-type-no-unknown": [
      true,
      {
        ignoreTypes: ["/.*-l$/"],
      },
    ],
    "shorthand-property-no-redundant-values": true,
    "string-no-newline": true,
    "time-min-milliseconds": 100,
    "unit-allowed-list": null,
    "unit-disallowed-list": null,
    "unit-no-unknown": true,
    "value-keyword-case": "lower",
    "value-no-vendor-prefix": true,
    "order/order": [
      "custom-properties",
      "dollar-variables",
      {
        type: "at-rule",
        hasBlock: false,
      },
      "declarations",
      {
        type: "at-rule",
        hasBlock: true,
      },
      "rules",
      {
        type: "at-rule",
        name: "include",
        parameter: "respond-to",
      },
    ],
    "order/properties-alphabetical-order": null,
    "order/properties-order": [
      "content",
      "will-change",
      "appearance",
      "clip",
      "clip-path",
      "visibility",
      "break-before",
      "page-break-before",
      "break-inside",
      "page-break-inside",
      "break-after",
      "page-break-after",
      "opacity",
      "display",
      "overflow",
      "overflow-x",
      "overflow-y",
      "-webkit-overflow-scrolling",
      "scroll-snap-type",
      "scroll-snap-align",
      "scroll-snap-stop",
      "scroll-margin",
      "scroll-padding",
      "grid",
      "grid-template",
      "grid-template-columns",
      "grid-template-rows",
      "grid-template-areas",
      "grid-gap",
      "column-gap",
      "grid-column-gap",
      "row-gap",
      "grid-row-gap",
      "justify-items",
      "grid-auto-columns",
      "grid-auto-rows",
      "grid-auto-flow",
      "grid-column",
      "grid-column-start",
      "grid-column-end",
      "grid-row",
      "grid-row-start",
      "grid-row-end",
      "grid-area",
      "justify-self",
      "align-self",
      "flex-direction",
      "flex-wrap",
      "flex-flow",
      "justify-content",
      "order",
      "flex",
      "flex-grow",
      "flex-shrink",
      "flex-basis",
      "align-self",
      "align-items",
      "align-content",
      "gap",
      "columns",
      "column-span",
      "column-width",
      "column-count",
      "column-fill",
      "column-gap",
      "column-rule",
      "column-rule-width",
      "column-rule-style",
      "column-rule-color",
      "table-layout",
      "border-collapse",
      "border-spacing",
      "list-style",
      "list-style-position",
      "list-style-type",
      "list-style-image",
      "counter-increment",
      "counter-reset",
      "float",
      "clear",
      "position",
      "isolation",
      "z-index",
      "inset",
      "inset-block",
      "inset-inline",
      "inset-block-start",
      "top",
      "inset-inline-end",
      "right",
      "inset-block-end",
      "bottom",
      "inset-inline-start",
      "left",
      "vertical-align",
      "box-sizing",
      "shape-outside",
      "shape-rendering",
      "inline-size",
      "width",
      "aspect-ratio",
      "min-inline-size",
      "min-width",
      "max-inline-size",
      "max-width",
      "block-size",
      "height",
      "min-block-size",
      "min-height",
      "max-block-size",
      "max-height",
      "line-clamp",
      "object-fit",
      "object-position",
      "outline",
      "outline-width",
      "outline-style",
      "outline-color",
      "outline-offset",
      "margin",
      "margin-block",
      "margin-inline",
      "margin-block-start",
      "margin-top",
      "margin-inline-end",
      "margin-right",
      "margin-block-end",
      "margin-bottom",
      "margin-inline-start",
      "margin-left",
      "border",
      "border-block",
      "border-inline",
      "border-block-start",
      "border-top",
      "border-inline-end",
      "border-right",
      "border-block-end",
      "border-bottom",
      "border-inline-start",
      "border-left",
      "border-width",
      "border-color",
      "border-style",
      "border-image",
      "border-radius",
      "border-block-width",
      "border-inline-width",
      "border-block-start-width",
      "border-top-width",
      "border-block-end-width",
      "border-right-width",
      "border-inline-end-width",
      "border-bottom-width",
      "border-inline-start-width",
      "border-left-width",
      "border-block-color",
      "border-inline-color",
      "border-block-start-color",
      "border-top-color",
      "border-right-color",
      "border-inline-end-color",
      "border-block-end-color",
      "border-bottom-color",
      "border-inline-start-color",
      "border-left-color",
      "border-block-style",
      "border-inline-style",
      "border-block-start-style",
      "border-top-style",
      "border-inline-end-style",
      "border-right-style",
      "border-block-end-style",
      "border-bottom-style",
      "border-inline-start-style",
      "border-left-style",
      "border-image-source",
      "border-image-slice",
      "border-image-width",
      "border-image-outset",
      "border-image-repeat",
      "border-block-start-image",
      "border-top-image",
      "border-inline-end-image",
      "border-right-image",
      "border-block-end-image",
      "border-bottom-image",
      "border-inline-start-image",
      "border-left-image",
      "border-corner-image",
      "border-start-start-image",
      "border-top-left-image",
      "border-start-end-image",
      "border-top-right-image",
      "border-end-end-image",
      "border-bottom-right-image",
      "border-end-start-image",
      "border-bottom-left-image",
      "border-start-start-radius",
      "border-top-left-radius",
      "border-start-end-radius",
      "border-top-right-radius",
      "border-end-end-radius",
      "border-bottom-right-radius",
      "border-end-start-radius",
      "border-bottom-left-radius",
      "border-boundary",
      "padding",
      "padding-block",
      "padding-inline",
      "padding-block-start",
      "padding-top",
      "padding-inline-end",
      "padding-right",
      "padding-block-end",
      "padding-bottom",
      "padding-inline-start",
      "padding-left",
      "box-shadow",
      "stroke",
      "stroke-align",
      "stroke-alignment",
      "stroke-break",
      "stroke-color",
      "stroke-dash-corner",
      "stroke-dash-justify",
      "stroke-dashadjust",
      "stroke-dasharray",
      "stroke-dashcorner",
      "stroke-dashoffset",
      "stroke-image",
      "stroke-linecap",
      "stroke-linejoin",
      "stroke-miterlimit",
      "stroke-opacity",
      "stroke-origin",
      "stroke-position",
      "stroke-repeat",
      "stroke-size",
      "stroke-width",
      "transform",
      "transform-origin",
      "zoom",
      "transform-style",
      "-moz-osx-font-smoothing",
      "-webkit-font-smoothing",
      "font",
      "font-family",
      "src",
      "font-feature-settings",
      "font-kerning",
      "font-size",
      "font-size-adjust",
      "font-stretch",
      "font-style",
      "font-variant",
      "font-variant-numeric",
      "font-weight",
      "hyphens",
      "letter-spacing",
      "line-height",
      "overflow-wrap",
      "quotes",
      "text-align",
      "text-align-last",
      "text-decoration",
      "text-decoration-skip",
      "text-emphasis",
      "text-emphasis-color",
      "text-emphasis-position",
      "text-emphasis-style",
      "text-indent",
      "text-justify",
      "text-outline",
      "text-overflow",
      "text-rendering",
      "text-shadow",
      "text-size-adjust",
      "text-transform",
      "white-space",
      "word-break",
      "word-spacing",
      "word-wrap",
      "fill",
      "color",
      "accent-color",
      "background",
      "background-color",
      "background-image",
      "background-attachment",
      "background-repeat",
      "background-position",
      "background-position-x",
      "background-position-y",
      "background-clip",
      "background-origin",
      "background-size",
      "animation",
      "animation-name",
      "animation-duration",
      "animation-timing-function",
      "animation-delay",
      "animation-iteration-count",
      "animation-direction",
      "animation-fill-mode",
      "animation-play-state",
      "backface-visibility",
      "cursor",
      "filter",
      "perspective",
      "pointer-events",
      "resize",
      "touch-action",
      "transition",
      "user-select",
      "-webkit-tap-highlight-color",
    ],
  },
};
