---
name: Changelog and Release
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action
          include-v-in-tag: false
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          pull-request-title-pattern: "chore: release ${version}"
  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          registry-url: https://npm.pkg.github.com
          cache: npm
          scope: "@jkimmeyer"
      - name: Install Node dependencies
        run: npm ci
      - name: Build Files
        run: npm run build
        # The .npmrc contains a read-only auth token for the github registry,
        # but we need to use the GITHUB_TOKEN for publishing.
        # Since the token from the .npmrc is used by default, we need to remove this file and re-setup our environment.
      - name: Remove .npmrc
        run: rm -f .npmrc
      - name: Setup environment for publishing
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          registry-url: https://npm.pkg.github.com
          scope: "@jkimmeyer"
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
