---
name: Validate PR title
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          # When adding types here, also extend the changelog-types configuration in `changelog.yml`
          types: |
            feat
            fix
            chore
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
